services:
  web:
    image: odoo:17
    env_file:
      - .env    
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    environment:
      - HOST=db
      - USER=${DB_USER}  
      - PASSWORD=${DB_PASSWORD}
      - DB_HOST=db  # Para indicar el host de la base de datos
      - DB_PORT=5432  # Puerto por defecto de PostgreSQL
      - DB_NAME=${DB_NAME}  # Nombre de la base de datos
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      
volumes:
  odoo-web-data:
  odoo-db-data:


