services:
  web:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    env_file: .env  # Carga las variables de entorno desde el archivo .env
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}  
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432  # Puerto por defecto de PostgreSQL

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      
volumes:
  odoo-web-data:
  odoo-db-data:



