name: Deploy to Server

on:
  push:
    branches:
      - main  # El flujo se ejecutará cuando haya un push en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-docker@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t walterhalm/peluqueria-canina:latest .
          docker push walterhalm/peluqueria-canina:latest
